spring:
  application:
    name: "todo"

  profiles:
    active: "dev"

  jpa:
    database-platform: "org.hibernate.community.dialect.SQLiteDialect"

    hibernate:
      ddl-auto: update

    show-sql: true


datasource:
  driver-class-name: "org.sqlite.JDBC"
  url: "jdbc:sqlite:db.sqlite3"
